package xzydemo.demo.domain;

public class Account1DOWithBLOBs extends Account1DO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.picture
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    private byte[] picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.self_introduce
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    private String selfIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.require
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    private String requirement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.picture
     *
     * @return the value of account.picture
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.picture
     *
     * @param picture the value for account.picture
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.self_introduce
     *
     * @return the value of account.self_introduce
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    public String getSelfIntroduce() {
        return selfIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.self_introduce
     *
     * @param selfIntroduce the value for account.self_introduce
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    public void setSelfIntroduce(String selfIntroduce) {
        this.selfIntroduce = selfIntroduce == null ? null : selfIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.require
     *
     * @return the value of account.require
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.require
     *
     * @param requirement the value for account.require
     *
     * @mbg.generated Sun Oct 20 21:55:03 CST 2019
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }




    @Override
    public boolean equals(Object obj) {
        if ( !(obj instanceof Account1DOWithBLOBs))
            return false;
        if (this.getAccountid().matches(((Account1DOWithBLOBs) obj).getAccountid()))
            return true;
        else return false;
    }
}